/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplcaciones;

import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import practica1.Empleado;
import practica2.Cobrador;
import practica2.Gerente;

/**
 *
 * @author USER
 */
public class AppEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form AppEmpleado
     */
    public AppEmpleado() {
        initComponents();
        tCedula.selectAll();
        lista = new ArrayList<>();
        tNombre.setForeground(Color.gray);
        tApellido.setForeground(Color.gray);
        tSalario.setText(""+Empleado.SALARIO_MINIMO);
        buttonGroup1.add(rGerente);
        buttonGroup1.add(rCobrador);
        rGerente.setSelected(true);
        tCampo1.setText(""+Empleado.SALARIO_MINIMO*2);
        bTrabajar.setEnabled(false);
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        bSalir = new javax.swing.JButton();
        lTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tCedula = new javax.swing.JTextField();
        tNombre = new javax.swing.JTextField();
        tApellido = new javax.swing.JTextField();
        tEdad = new javax.swing.JTextField();
        tPeso = new javax.swing.JTextField();
        cCoronavirus = new javax.swing.JCheckBox();
        tSalario = new javax.swing.JTextField();
        cDpto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tResultado = new javax.swing.JTextArea();
        bAgregar = new javax.swing.JButton();
        bCobrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        rGerente = new javax.swing.JRadioButton();
        rCobrador = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        tCampo1 = new javax.swing.JTextField();
        bMarcarEntrada = new javax.swing.JButton();
        bTrabajar = new javax.swing.JButton();

        jButton2.setText("Agregar Empleado");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App de Prueba de Empleados");
        setBackground(new java.awt.Color(255, 153, 0));
        setBounds(new java.awt.Rectangle(400, 75, 586, 524));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 216, 242));
        setMaximumSize(new java.awt.Dimension(586, 524));
        setMinimumSize(new java.awt.Dimension(586, 524));
        setName("CargarEmpleados"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(586, 524));

        bSalir.setMnemonic('s');
        bSalir.setText("Salir");
        bSalir.setToolTipText("Salir de la Aplicacion");
        bSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalirMouseClicked(evt);
            }
        });
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        lTitulo.setBackground(new java.awt.Color(240, 203, 105));
        lTitulo.setDisplayedMnemonic('1');
        lTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 102, 0));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Aplicación para Cargar Empleados");
        lTitulo.setToolTipText("");
        lTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lTitulo.setAlignmentY(0.0F);
        lTitulo.setFocusable(false);
        lTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Cedula");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Edad");

        jLabel6.setText("Peso");

        jLabel7.setText("Coronavirus?");

        jLabel8.setText("Salario");

        jLabel9.setText("Departamento");

        tCedula.setBackground(new java.awt.Color(240, 240, 240));
        tCedula.setText("123456");
        tCedula.setToolTipText("");
        tCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tCedulaMouseClicked(evt);
            }
        });

        tNombre.setText("Caleb");

        tApellido.setText("Trepowski");
        tApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tApellidoFocusGained(evt);
            }
        });
        tApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tApellidoActionPerformed(evt);
            }
        });

        tEdad.setText("20");
        tEdad.setToolTipText("");

        tPeso.setText("65");

        cCoronavirus.setText("Marque si tiene síntomas");

        tSalario.setText("2500000");

        cDpto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventas", "Cobranza", "Producción", "Informática" }));
        cDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDptoActionPerformed(evt);
            }
        });

        tResultado.setColumns(20);
        tResultado.setRows(5);
        tResultado.setFocusable(false);
        jScrollPane1.setViewportView(tResultado);

        bAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bAgregar.setForeground(new java.awt.Color(255, 102, 0));
        bAgregar.setText("Agregar Empleado");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bCobrar.setForeground(new java.awt.Color(255, 102, 0));
        bCobrar.setText("Cobrar Salario");
        bCobrar.setMaximumSize(new java.awt.Dimension(137, 23));
        bCobrar.setMinimumSize(new java.awt.Dimension(137, 23));
        bCobrar.setPreferredSize(new java.awt.Dimension(137, 23));
        bCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCobrarActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo de Empleado");

        rGerente.setText("Gerente");
        rGerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rGerenteMouseClicked(evt);
            }
        });
        rGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rGerenteActionPerformed(evt);
            }
        });

        rCobrador.setText("Cobrador");
        rCobrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rCobradorMouseClicked(evt);
            }
        });
        rCobrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCobradorActionPerformed(evt);
            }
        });

        jLabel11.setText("Sobre sueldo");

        tCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCampo1ActionPerformed(evt);
            }
        });

        bMarcarEntrada.setText("Marcar Entrada");
        bMarcarEntrada.setMaximumSize(new java.awt.Dimension(137, 23));
        bMarcarEntrada.setMinimumSize(new java.awt.Dimension(137, 23));
        bMarcarEntrada.setPreferredSize(new java.awt.Dimension(137, 23));
        bMarcarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMarcarEntradaActionPerformed(evt);
            }
        });

        bTrabajar.setText("Trabajar");
        bTrabajar.setPreferredSize(new java.awt.Dimension(137, 23));
        bTrabajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTrabajarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(67, 67, 67)
                                    .addComponent(rGerente)
                                    .addGap(18, 18, 18)
                                    .addComponent(rCobrador))
                                .addComponent(jLabel5)
                                .addComponent(tEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tPeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel11))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cDpto, javax.swing.GroupLayout.Alignment.TRAILING, 0, 291, Short.MAX_VALUE)
                                        .addComponent(tSalario)
                                        .addComponent(tApellido)
                                        .addComponent(tNombre)
                                        .addComponent(tCedula)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(47, 47, 47)
                                            .addComponent(cCoronavirus))
                                        .addComponent(tCampo1))))
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bMarcarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bTrabajar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cCoronavirus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rGerente)
                    .addComponent(rCobrador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cDpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMarcarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTrabajar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDptoActionPerformed

    private void tApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tApellidoFocusGained
        // TODO add your handling code here:
        tApellido.selectAll();
    }//GEN-LAST:event_tApellidoFocusGained

    private void tApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tApellidoActionPerformed

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        int ced = 0;
        try {
            ced = Integer.parseInt( tCedula.getText() );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la cedula");
            tCedula.selectAll();
            tCedula.requestFocus();
            return;
        }
        String nom = tNombre.getText();
        if(nom.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre");
            tNombre.requestFocus();
            return; 
        }
        
        String ape = tApellido.getText();
        int edad = Integer.parseInt( tEdad.getText() );
        float peso = Float.parseFloat( tPeso.getText() );
        int sal = Integer.parseInt( tSalario.getText() );
        String dep = cDpto.getSelectedItem().toString();
        boolean cVirus = cCoronavirus.isSelected();
        int ss = 0;
        try{
            ss = Integer.parseInt(tCampo1.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "El monto debe ser numérico");
            tCampo1.requestFocus();
                    
        }
        
                  
        
        if(rGerente.isSelected())
            e = new Gerente(ced,nom,ape,edad,sal,dep,ss);
        else if(rCobrador.isSelected())
            e = new Cobrador(ced, nom, ape, edad, sal, dep, ss);
        e.setPeso(peso);
        e.setCoronavirus(cVirus);
        
        if(!lista.contains(e)){
            lista.add(e);
            tResultado.append(e.toString());
            tResultado.append("------------------\n");
            bTrabajar.setEnabled(true);
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bSalirMouseClicked

    
    
    
    private void bCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCobrarActionPerformed
        // TODO add your handling code here:
         if (e != null) {
            DecimalFormat df = new DecimalFormat();
            tResultado.append(e.cobrarSalario());
            tResultado.append(" - IPS: ");
            String ips = df.format(e.IPS());
            tResultado.append(ips+"\n");
         }
    }//GEN-LAST:event_bCobrarActionPerformed

    private void tCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tCedulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tCedulaMouseClicked

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        if ( JOptionPane.showConfirmDialog(this,"Esta seguro de salir","Salir", JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void rGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rGerenteActionPerformed

    private void rCobradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rCobradorMouseClicked
        jLabel11.setText("Comision");
        tCampo1.setText("1000000");
        cDpto.setSelectedIndex(1);
        cDpto.setEnabled(false);
    }//GEN-LAST:event_rCobradorMouseClicked

    private void rGerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rGerenteMouseClicked
        jLabel11.setText("Sobre sueldo");
        tCampo1.setText(""+Empleado.SALARIO_MINIMO);
        cDpto.setSelectedIndex(0);
        cDpto.setEnabled(true);
    }//GEN-LAST:event_rGerenteMouseClicked

    private void tCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCampo1ActionPerformed

    private void rCobradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCobradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rCobradorActionPerformed

    private void bMarcarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMarcarEntradaActionPerformed
        if(e != null)
            tResultado.append(e.marcarEntrada().toString()+"\n");
        else
            JOptionPane.showMessageDialog(this, "No Existe Empleado",
                    "Error!",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bMarcarEntradaActionPerformed

    private void bTrabajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTrabajarActionPerformed
        tResultado.append(e.trabajar()+"\n");
    }//GEN-LAST:event_bTrabajarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bCobrar;
    private javax.swing.JButton bMarcarEntrada;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bTrabajar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cCoronavirus;
    private javax.swing.JComboBox<String> cDpto;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JRadioButton rCobrador;
    private javax.swing.JRadioButton rGerente;
    private javax.swing.JTextField tApellido;
    private javax.swing.JTextField tCampo1;
    private javax.swing.JTextField tCedula;
    private javax.swing.JTextField tEdad;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tPeso;
    private javax.swing.JTextArea tResultado;
    private javax.swing.JTextField tSalario;
    // End of variables declaration//GEN-END:variables
    private Empleado e;
    ArrayList<Empleado> lista;
    
}
